[package]
name = "csesfi-coin_combinations_1"
version = "0.1.0"
authors = ["Thibault Nocchi <1619359+ThibaultNocchi@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
